<?php

$title = $this->translate('Sign Up');
$this->headMeta()->appendName('keywords', 'Sign Up, Create, Join, New Account');
$this->headMeta()->appendName('description', 'Create a new account');
$this->headTitle($this->escapeHtml($title));

$signInForm = $this->sign_in_form;
$signInForm->prepare();

$forgotPasswordForm = $this->forgot_password_form;
$forgotPasswordForm->prepare();

$registrationForm = $this->registration_form;
$registrationForm->prepare();

?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Точка входа">
    <link rel="SHORTCUT ICON" href="<?= $this->basePath('img/locust-solid.svg') ?>">
    <title>OggyWeb</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta name="theme-color" content="#7952b3">
    <?= $this->headLink([
        'rel'  => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/locust-solid.svg'
    ])
        ->prependStylesheet($this->basePath('css/test.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>
</head>
<body class="text-center">
<main class="form-signin" style="padding-top: 150px">
    <div id='sign'>
        <img class="mb-4" src="<?= $this->basePath('img/locust-solid.svg') ?>" alt="" width="72" height="57">
        <h1 class="h3 mb-3 fw-normal">Please enter fields</h1>
        <?= $this->form()->openTag($signInForm); ?>
        <div class="mb-3 text-lg-left" style="padding-top: 25px">
            <?= $this->formLabel($signInForm->get('email')); ?>
            <div class="form-group">
                <?= $this->formEmail($signInForm->get('email')); ?>
            </div>
            <div class="text-danger">
                <?= $this->formElementErrors($signInForm->get('email')); ?>
            </div>
        </div>
        <div class="mb-3 text-lg-left">
            <?= $this->formLabel($signInForm->get('password')); ?>
            <div class="form-group">
                <?= $this->formPassword($signInForm->get('password')); ?>
            </div>

            <div class="text-danger">
                <?= $this->formElementErrors($signInForm->get('password')); ?>
            </div>
        </div>
        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <div class="w-100 btn btn-lg btn-primary">
            <?= $this->formSubmit($signInForm->get('sign_in')); ?>
        </div>
        <?= $this->form()->closeTag(); ?>
        <button class="btn" onclick="show('registration')" type="button">Create account?</button>
        <button class="btn" onclick="show('forgot')" type="button">Forgot password?</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2021–2022</p>
    </div>
    <div hidden id="registration">
        <?= $this->form()->openTag($registrationForm); ?>
        <img class="mb-4" src="<?= $this->basePath('img/locust-solid.svg') ?>" alt="" width="72" height="57">
        <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

        <div class="mb-3 text-lg-left">
            <?= $this->formLabel($registrationForm->get('email')); ?>
            <div class="form-group">
                <?= $this->formEmail($registrationForm->get('email')); ?>
            </div>

            <div class="text-danger">
                <?= $this->formElementErrors($registrationForm->get('email')); ?>
            </div>
        </div>

        <div class="mb-3 text-lg-left">
            <?= $this->formLabel($registrationForm->get('dropdown')); ?>
            <div class="form-group">
                <?= $this->formSelect($registrationForm->get('dropdown')); ?>
            </div>
        </div>


        <div class="mb-3 text-lg-left">
            <?= $this->formLabel($registrationForm->get('password')); ?>
            <div class="form-group">
                <?= $this->formPassword($registrationForm->get('password')); ?>
            </div>

            <div class="text-danger">
                <?= $this->formElementErrors($registrationForm->get('password')); ?>
            </div>
        </div>

        <div class="mb-3 text-lg-left">
            <?= $this->formLabel($registrationForm->get('confirm_password')); ?>
            <div class="form-group">
                <?= $this->formPassword($registrationForm->get('confirm_password')); ?>
            </div>

            <div class="text-danger">
                <?= $this->formElementErrors($registrationForm->get('confirm_password')); ?>
            </div>
        </div>
        <p class="demo"></p>
        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <div class="w-100 btn btn-lg btn-primary">
            <?= $this->formSubmit($registrationForm->get('create_account')); ?>
        </div>
        <?= $this->form()->closeTag(); ?>
        <button class="btn btn-default btn-login" onclick="show('sign')" type="button">Login?</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2021–2022</p>

    </div>
    <div hidden id="forgot">
        <?= $this->form()->openTag($forgotPasswordForm); ?>
        <img class="mb-4" src="<?= $this->basePath('img/locust-solid.svg') ?>" alt="" width="72" height="57">
        <h1 class="h3 mb-3 fw-normal">Please enter email</h1>
        <div class="mb-3 text-lg-left" style="padding-top: 25px">
            <?= $this->formLabel($forgotPasswordForm->get('email')); ?>
            <div class="form-group">
                <?= $this->formEmail($forgotPasswordForm->get('email')); ?>
            </div>
            <div class="text-danger">
                <?= $this->formElementErrors($forgotPasswordForm->get('email')); ?>
            </div>
        </div>
        <div class="w-100 btn btn-lg btn-primary">
            <?= $this->formSubmit($forgotPasswordForm->get('forgot_password')); ?>
        </div>
        <?= $this->form()->closeTag(); ?>
        <p class="demo"></p>
        <button class="btn btn-default btn-login" onclick="show('sign')" type="button">Get back</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2021–2022</p>
    </div>
</main>
</body>
</html>