<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Точка входа">
    <link rel="SHORTCUT ICON" href="<?= $this->basePath('img/locust-solid.svg') ?>">
    <title>OggyWeb</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta name="theme-color" content="#7952b3">
    <?= $this->headLink([
        'rel'  => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/app.css'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>
<body>
<?= $this->content ?>
<?= $this->inlineScript()
    ->prependFile($this->basePath('js/sidebars.js'))
    ->prependFile($this->basePath('js/profile.js'))
    ->prependFile($this->basePath('js/chats.js'))
    ->prependFile($this->basePath('js/users.js'))
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
</body>
</html>