<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="Точка входа">
    <link rel="SHORTCUT ICON" href="<?= $this->basePath('img/locust-solid.svg') ?>">
    <title>OggyWeb</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <?= $this->headLink([
        'rel'  => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/profile.css'))
        ->prependStylesheet($this->basePath('css/chats_DEV.css'))
        ->prependStylesheet($this->basePath('css/sidebars.css'))
        ->prependStylesheet($this->basePath('css/test.css'))
    ?>
    <!doctype html>
    <html lang="en">
<body>
<main>
    <div class=" p-3 bg-white " style="width: 280px;">
        <a href="/profile" class="d-flex align-items-center pb-3 mb-3 link-dark text-decoration-none border-bottom">
            <svg class="bi me-2" width="30" height="24">
                <use href="/pictures/locust-solid.svg"/>
            </svg>
            <span class="fs-5 fw-semibold">Collapsible</span>
        </a>
        <ul class="list-unstyled ps-0">
            <li class="mb-1">
                <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse"
                        data-bs-target="#home-collapse" aria-expanded="true">
                    Home
                </button>
                <div class="collapse show" id="home-collapse">
                    <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                        <li><a href="../user-list" class="link-dark rounded">Users</a></li>
                        <li><a href="../chat/index/2" class="link-dark rounded">Chats</a></li>
                    </ul>
                </div>
            </li>
            </li>
            <li class="border-top my-3"></li>
            <li class="mb-1">
                <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse"
                        data-bs-target="#account-collapse" aria-expanded="false">
                    Account
                </button>
                <div class="collapse" id="account-collapse">
                    <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                        <li><a href="../password" class="link-dark rounded">Change Password</a></li>
                        <li><a href="../profile-edit/edit" class="link-dark rounded">Profile settings</a></li>
                        <li><a href="../login" class="link-dark rounded">Sign out</a></li>
                    </ul>
                </div>
            </li>
            <li class="border-top my-3"></li>
            <li class="mb-1">
                <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse"
                        data-bs-target="#orders-collapse" aria-expanded="false">
                    Admin
                </button>
                <div class="collapse" id="orders-collapse">
                    <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                        <li><a href="../title/index" class="link-dark rounded">Title Settings</a></li>
                        <li><a href="../admin-list" class="link-dark rounded">Users Settings</a></li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
    <div class="b-example-divider"></div>
</main>
<div class="">
    <?= $this->content ?>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
<?= $this->inlineScript()
    ->prependFile($this->basePath('js/sidebars.js'))
    ->prependFile($this->basePath('js/profile.js'))
    ->prependFile($this->basePath('js/chats.js'))
    ->prependFile($this->basePath('js/users.js'))
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
</body>
</html>